SELECT CITY, AREA, AVG(ENVIRONMENTAL_IMPACT) AS AVG_ENVIRONMENTAL_IMPACT,
        AVG(PUBLIC_TRANSPORT_USAGE) AS AVG_PUBLIC_TRANSPORT, AVG(PARKING_USAGE) AS AVG_PARKING,
        AVG(PEDESTRIAN_CYCLIST_COUNT) AS AVG_PEDESTRIAN_COUNT, AVG(TRAFFIC_SIGNAL_COMPLIANCE) AS AVG_SIGNAL_COMPLIANCE

FROM {{ ref('traffic_events_clean') }}
GROUP BY CITY, AREA