SELECT CITY, COUNT(*) AS TOTAL_EVENTS,AVG(TRAFFIC_VOLUME) AS AVG_TRAFFIC_VOLUME,
        AVG(AVERAGE_SPEED) AS AVG_SPEED,AVG(TRAVEL_TIME_INDEX) AS AVG_TRAVEL_TIME_INDEX,
        AVG(ROAD_CAPACITY_UTILIZATION) AS AVG_CAPACITY_UTILIZATION,
        AVG(PUBLIC_TRANSPORT_USAGE) AS AVG_PUBLIC_TRANSPORT_USAGE,
        SUM(INCIDENT_REPORTS) AS TOTAL_INCIDENTS

FROM {{ ref('traffic_events_clean') }}
GROUP BY CITY