SELECT CITY, AREA, ROAD_NAME, SUM(INCIDENT_REPORTS) AS TOTAL_INCIDENTS,
AVG(TRAFFIC_VOLUME) AS AVG_TRAFFIC, AVG(AVERAGE_SPEED) AS AVG_SPEED,
MAX(EVENT_TIMESTAMP) AS LAST_INCIDENT_TIME

FROM {{ ref('traffic_events_clean') }}
WHERE INCIDENT_REPORTS > 0
GROUP BY CITY, AREA, ROAD_NAME