SELECT CITY,AREA,ROAD_NAME, CONGESTION_LEVEL, AVG(TRAFFIC_VOLUME) AS AVG_TRAFFIC,
        AVG(AVERAGE_SPEED) AS AVG_SPEED,AVG(TRAVEL_TIME_INDEX) AS AVG_TRAVEL_TIME_INDEX,
        AVG(ROAD_CAPACITY_UTILIZATION) AS CAPACITY_UTILIZATION, COUNT(*) AS TOTAL_EVENTS

FROM {{ ref('traffic_events_clean') }}
GROUP BY CITY, AREA, ROAD_NAME, CONGESTION_LEVEL