SELECT TIMEBLOCK, CITY, COUNT(*) AS TOTAL_EVENTS, AVG(TRAFFIC_VOLUME) AS AVG_TRAFFIC,
       AVG(AVERAGE_SPEED) AS AVG_SPEED, AVG(TRAVEL_TIME_INDEX) AS AVG_DELAY,
       SUM(INCIDENT_REPORTS) AS INCIDENTS

FROM {{ ref('traffic_events_clean') }}
GROUP BY TIMEBLOCK,CITY