{{
    config(
        materialized='incremental',
        unique_key='EVENT_ID'
    )
}}

SELECT EVENT_ID, SENSOR_ID, TRIM(CITY) AS CITY, TRIM(AREA) AS AREA, TRIM(ROAD_NAME) AS ROAD_NAME,
        TRAFFIC_VOLUME,AVERAGE_SPEED,TRAVEL_TIME_INDEX,CONGESTION_LEVEL,ROAD_CAPACITY_UTILIZATION,
        INCIDENT_REPORTS,ENVIRONMENTAL_IMPACT,PUBLIC_TRANSPORT_USAGE,TRAFFIC_SIGNAL_COMPLIANCE,PARKING_USAGE,
        PEDESTRIAN_CYCLIST_COUNT,WEATHER,ROADWORK,TIMEBLOCK,TRAFFIC_SITUATION,EVENT_TIMESTAMP,
        LOAD_TIME,CURRENT_TIMESTAMP() AS DBT_PROCESSED_TIME

FROM {{ ref('stg_traffic_events') }}
WHERE EVENT_ID IS NOT NULL

{% if is_incremental() %}
AND EVENT_TIMESTAMP >
(
    SELECT COALESCE(MAX(EVENT_TIMESTAMP),'2022-01-01')
    FROM {{ this }}
)
{% endif %}